# Generated by Django 5.0.1 on 2024-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
